In [ ]:
# link to repo

dataRepo = 'https://github.com/Journey-of-Success/TAREA3/raw/main/appendData/'

In [ ]:
# creating file names into a list:
numbers=range(1,5)
fileNames=['level'+str(number)+'.xlsx' for number in numbers]

# list of file names
fileNames

['level1.xlsx', 'level2.xlsx', 'level3.xlsx', 'level4.xlsx']

In [ ]:
# creating the url to each file:
alltheLinks=[dataRepo+fn for fn in fileNames]
alltheLinks

['https://github.com/Journey-of-Success/TAREA3/raw/main/appendData/level1.xlsx',
 'https://github.com/Journey-of-Success/TAREA3/raw/main/appendData/level2.xlsx',
 'https://github.com/Journey-of-Success/TAREA3/raw/main/appendData/level3.xlsx',
 'https://github.com/Journey-of-Success/TAREA3/raw/main/appendData/level4.xlsx']

In [ ]:
#to save each data in a list allDFs we need openpyxl and xlrd for excel
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [ ]:
# creating list of DFs
import pandas as pd

allDFs=[pd.read_excel(link,engine='openpyxl') for link in alltheLinks]

In [ ]:
allDFs[0].columns=allDFs[0].iloc[3, :].tolist()
allDFs[0].head()

,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank,NaN
4,NaN,NaN,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN,NaN

In [ ]:
column_names= allDFs[0].columns.tolist()
column_names

['HDI rank',
 'Country',
 'Human Development Index (HDI) ',
 nan,
 'Life expectancy at birth',
 nan,
 'Expected years of schooling',
 nan,
 'Mean years of schooling',
 nan,
 'Gross national income (GNI) per capita',
 nan,
 'GNI per capita rank minus HDI rank',
 nan,
 'HDI rank',
 nan]

In [ ]:
# añadir un contador para contar 'HDI rank'
count = 0

# Iterando la lista para contar
for i, col in enumerate(column_names):
    if col == 'HDI rank':
        count += 1
        # si aparece por segunda vez, renombrar por 'HDI rank.1'
        if count == 2:
            column_names[i] = 'HDI rank.1'
            break

column_names

['HDI rank',
 'Country',
 'Human Development Index (HDI) ',
 nan,
 'Life expectancy at birth',
 nan,
 'Expected years of schooling',
 nan,
 'Mean years of schooling',
 nan,
 'Gross national income (GNI) per capita',
 nan,
 'GNI per capita rank minus HDI rank',
 nan,
 'HDI rank.1',
 nan]

In [ ]:
allDFs[0].columns=column_names
allDFs[0].head()

,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank.1,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank,NaN
4,NaN,NaN,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN,NaN

In [ ]:
#funcion para eliminar filas no necesarias
def clean_rows(df, column_name):
        df[column_name] = pd.to_numeric(df[column_name], errors='coerce')
        cleaned_df = df.dropna(subset=[column_name])
        return cleaned_df

In [ ]:
# Cleaning each Data Frame using the function
allDFs = [clean_rows(df, 'HDI rank') for df in allDFs]

In [ ]:
allDFs[0].head(3)

,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank.1,NaN
6,1.0,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3,VERY HIGH HUMAN DEVELOPMENT
7,2.0,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1,VERY HIGH HUMAN DEVELOPMENT
8,3.0,Iceland,0.959,NaN,82.6782,NaN,19.163059,c,13.76717,NaN,55782.04981,NaN,11,NaN,2,VERY HIGH HUMAN DEVELOPMENT

In [ ]:
allDFs[1].head(3)

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Unnamed: 6,Gross national income (GNI) per capita,Unnamed: 8,GNI per capita rank minus HDI rank,Unnamed: 10,HDI rank.1
2,67.0,Albania,0.796,76.4626,14.44800,11.286455,e,14131.11039,NaN,17.0,NaN,68.0
3,68.0,Bulgaria,0.795,71.7980,13.89729,11.413180,NaN,23078.95595,NaN,-8.0,NaN,64.0
4,68.0,Grenada,0.795,74.9362,18.66202,9.032104,l,13483.57740,NaN,18.0,NaN,70.0

In [ ]:
allDFs[2].head(3)

,HDI rank,Country,Human Development Index (HDI),Unnamed: 3,Life expectancy at birth,Unnamed: 5,Expected years of schooling,Unnamed: 7,Mean years of schooling,Unnamed: 9,Gross national income (GNI) per capita,Unnamed: 11,GNI per capita rank minus HDI rank,Unnamed: 13,HDI rank.1
2,116.0,Philippines,0.699,NaN,69.2664,NaN,13.126570,NaN,8.96910,NaN,8920.428468,NaN,-3.0,NaN,113.0
3,117.0,Botswana,0.693,NaN,61.1409,NaN,12.265138,e,10.34000,NaN,16198.318410,NaN,-43.0,NaN,110.0
4,118.0,Bolivia (Plurinational State of),0.692,NaN,63.6304,NaN,14.946971,NaN,9.82775,NaN,8111.190194,NaN,0.0,NaN,119.0

In [ ]:
allDFs[3].head(3)

,HDI rank,Country,Unnamed: 2,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,le
0,160,Tanzania (United Republic of),LOW HUMAN DEVELOPMENT,0.549,66.2007,9.221490,6.372899,2664.329096,7,NaN
1,161,Pakistan,LOW HUMAN DEVELOPMENT,0.544,66.0979,8.658350,4.536330,4623.705430,-19,NaN
2,162,Togo,LOW HUMAN DEVELOPMENT,0.539,61.6194,12.950494,5.016807,2166.619062,12,NaN

In [ ]:
# saving column names
allColumnNames=[]
for df in allDFs:
    allColumnNames.append(set(df.columns))

In [ ]:
# checking how many columns per df
[len(cols) for cols in allColumnNames]

[11, 12, 15, 10]

In [ ]:
# details of common columns
commonColumns=set.intersection(*allColumnNames)
len(commonColumns),commonColumns

(8,
 {'Country',
  'Expected years of schooling',
  'GNI per capita rank minus HDI rank',
  'Gross national income (GNI) per capita',
  'HDI rank',
  'Human Development Index (HDI) ',
  'Life expectancy at birth',
  'Mean years of schooling'})

In [ ]:
# all minus the common
set.union(*allColumnNames)-commonColumns

{'HDI rank.1',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 13',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'le',
 nan,
 nan}

In [ ]:
# DFs with the common columns
allDFs_sameNames=[df.loc[:,list(commonColumns)] for df in allDFs]
allDFs_sameNames=[df.reset_index(drop=True) for df in allDFs_sameNames]

In [ ]:
# appending
allDFsConcat=pd.concat(allDFs_sameNames)
allDFsConcat

,Gross national income (GNI) per capita,Life expectancy at birth,Expected years of schooling,GNI per capita rank minus HDI rank,Mean years of schooling,Country,HDI rank,Human Development Index (HDI)
0,66933.00454,83.9872,16.500299,5,13.85966,Switzerland,1.0,0.962
1,64660.10622,83.2339,18.1852,6,13.00363,Norway,2.0,0.961
2,55782.04981,82.6782,19.163059,11,13.76717,Iceland,3.0,0.959
3,62606.8454,85.4734,17.27817,6,12.22621,"Hong Kong, China (SAR)",4.0,0.952
4,49238.43335,84.5265,21.05459,18,12.72682,Australia,5.0,0.951
...,...,...,...,...,...,...,...,...
27,731.786709,61.6627,10.722722,4,3.129267,Burundi,187.0,0.426
28,966.058611,53.8947,8.040172,1,4.334,Central African Republic,188.0,0.404
29,1239.866936,61.5763,6.957112,-3,2.116717,Niger,189.0,0.4
30,1364.169417,52.5254,8.035914,-7,2.573774,Chad,190.0,0.394
31,767.787,54.9752,5.54251,-1,5.72614,South Sudan,191.0,0.385

In [ ]:
#para ordenar
#usamos inplace para guardar los datos (modificar)
allDFsConcat.set_index(['HDI rank', 'Country'],inplace=True)
allDFsConcat.head()

KeyError: "None of ['HDI rank'] are in the columns"

In [ ]:
# ordering column names alphabetically
allDFsConcat.sort_index(axis=1,inplace=True) # by row index will be axis=0
allDFsConcat

,,Expected years of schooling,GNI per capita rank minus HDI rank,Gross national income (GNI) per capita,Human Development Index (HDI),Life expectancy at birth,Mean years of schooling
HDI rank,Country,,,,,,
1.0,Switzerland,16.500299,5,66933.00454,0.962,83.9872,13.85966
2.0,Norway,18.1852,6,64660.10622,0.961,83.2339,13.00363
3.0,Iceland,19.163059,11,55782.04981,0.959,82.6782,13.76717
4.0,"Hong Kong, China (SAR)",17.27817,6,62606.8454,0.952,85.4734,12.22621
5.0,Australia,21.05459,18,49238.43335,0.951,84.5265,12.72682
...,...,...,...,...,...,...,...
187.0,Burundi,10.722722,4,731.786709,0.426,61.6627,3.129267
188.0,Central African Republic,8.040172,1,966.058611,0.404,53.8947,4.334
189.0,Niger,6.957112,-3,1239.866936,0.4,61.5763,2.116717
190.0,Chad,8.035914,-7,1364.169417,0.394,52.5254,2.573774
191.0,South Sudan,5.54251,-1,767.787,0.385,54.9752,5.72614

In [ ]:
# indexes will be columns
allDFsConcat.reset_index(inplace=True)
allDFsConcat

,HDI rank,Country,Expected years of schooling,GNI per capita rank minus HDI rank,Gross national income (GNI) per capita,Human Development Index (HDI),Life expectancy at birth,Mean years of schooling
0,1.0,Switzerland,16.500299,5,66933.00454,0.962,83.9872,13.85966
1,2.0,Norway,18.1852,6,64660.10622,0.961,83.2339,13.00363
2,3.0,Iceland,19.163059,11,55782.04981,0.959,82.6782,13.76717
3,4.0,"Hong Kong, China (SAR)",17.27817,6,62606.8454,0.952,85.4734,12.22621
4,5.0,Australia,21.05459,18,49238.43335,0.951,84.5265,12.72682
...,...,...,...,...,...,...,...,...
186,187.0,Burundi,10.722722,4,731.786709,0.426,61.6627,3.129267
187,188.0,Central African Republic,8.040172,1,966.058611,0.404,53.8947,4.334
188,189.0,Niger,6.957112,-3,1239.866936,0.4,61.5763,2.116717
189,190.0,Chad,8.035914,-7,1364.169417,0.394,52.5254,2.573774
190,191.0,South Sudan,5.54251,-1,767.787,0.385,54.9752,5.72614

Cleaning column names

In [ ]:
# see column names
allDFsConcat.columns.to_list()

['HDI rank',
 'Country',
 'Expected years of schooling',
 'GNI per capita rank minus HDI rank',
 'Gross national income (GNI) per capita',
 'Human Development Index (HDI) ',
 'Life expectancy at birth',
 'Mean years of schooling']

In [ ]:
# clean column names
allDFsConcat.columns=allDFsConcat.columns.str.replace('\(\w*\s*\w*\W*\)','',regex=True).str.title().str.replace("\s","_",regex=True)

#see
allDFsConcat.columns.to_list()

['Hdi_Rank',
 'Country',
 'Expected_Years_Of_Schooling',
 'Gni_Per_Capita_Rank_Minus_Hdi_Rank',
 'Gross_National_Income__Per_Capita',
 'Human_Development_Index__',
 'Life_Expectancy_At_Birth',
 'Mean_Years_Of_Schooling']

In [ ]:
# overwriting country
allDFsConcat.Country=allDFsConcat.Country.str.upper()

allDFsConcat.Country

0                   SWITZERLAND
1                        NORWAY
2                       ICELAND
3        HONG KONG, CHINA (SAR)
4                     AUSTRALIA
                 ...
186                     BURUNDI
187    CENTRAL AFRICAN REPUBLIC
188                       NIGER
189                        CHAD
190                 SOUTH SUDAN
Name: Country, Length: 191, dtype: object

Reviewing the data

In [ ]:
allDFsConcat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 8 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Hdi_Rank                            191 non-null    float64
 1   Country                             191 non-null    object
 2   Expected_Years_Of_Schooling         191 non-null    object
 3   Gni_Per_Capita_Rank_Minus_Hdi_Rank  191 non-null    object
 4   Gross_National_Income__Per_Capita   191 non-null    object
 5   Human_Development_Index__           191 non-null    object
 6   Life_Expectancy_At_Birth            191 non-null    object
 7   Mean_Years_Of_Schooling             191 non-null    object
dtypes: float64(1), object(7)
memory usage: 12.1+ KB

In [ ]:
allDFsConcat.Expected_Years_Of_Schooling.value_counts()

Expected_Years_Of_Schooling
16.500299    1
11.874620    1
12.991690    1
14.151910    1
12.671348    1
            ..
14.448000    1
13.897290    1
18.662020    1
15.713385    1
5.542510     1
Name: count, Length: 191, dtype: int64

In [ ]:
columns_to_convert = allDFsConcat.columns.difference(['Country'])
allDFsConcat[columns_to_convert] = allDFsConcat[columns_to_convert].apply(pd.to_numeric, errors='coerce')

In [ ]:
allDFsConcat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 8 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Hdi_Rank                            191 non-null    float64
 1   Country                             191 non-null    object
 2   Expected_Years_Of_Schooling         191 non-null    float64
 3   Gni_Per_Capita_Rank_Minus_Hdi_Rank  191 non-null    int64
 4   Gross_National_Income__Per_Capita   191 non-null    float64
 5   Human_Development_Index__           191 non-null    float64
 6   Life_Expectancy_At_Birth            191 non-null    float64
 7   Mean_Years_Of_Schooling             191 non-null    float64
dtypes: float64(6), int64(1), object(1)
memory usage: 12.1+ KB

In [ ]:
allDFsConcat

,Hdi_Rank,Country,Expected_Years_Of_Schooling,Gni_Per_Capita_Rank_Minus_Hdi_Rank,Gross_National_Income__Per_Capita,Human_Development_Index__,Life_Expectancy_At_Birth,Mean_Years_Of_Schooling
0,1.0,SWITZERLAND,16.500299,5,66933.004540,0.962,83.9872,13.859660
1,2.0,NORWAY,18.185200,6,64660.106220,0.961,83.2339,13.003630
2,3.0,ICELAND,19.163059,11,55782.049810,0.959,82.6782,13.767170
3,4.0,"HONG KONG, CHINA (SAR)",17.278170,6,62606.845400,0.952,85.4734,12.226210
4,5.0,AUSTRALIA,21.054590,18,49238.433350,0.951,84.5265,12.726820
...,...,...,...,...,...,...,...,...
186,187.0,BURUNDI,10.722722,4,731.786709,0.426,61.6627,3.129267
187,188.0,CENTRAL AFRICAN REPUBLIC,8.040172,1,966.058611,0.404,53.8947,4.334000
188,189.0,NIGER,6.957112,-3,1239.866936,0.400,61.5763,2.116717
189,190.0,CHAD,8.035914,-7,1364.169417,0.394,52.5254,2.573774
190,191.0,SOUTH SUDAN,5.542510,-1,767.787000,0.385,54.9752,5.726140

# Segunda Parte

In [ ]:
data=allDFsConcat.copy()

countryCodesLink = 'https://github.com/Journey-of-Success/TAREA3/raw/main/countryCODES.xlsx'
countryCodes=pd.read_excel(countryCodesLink)
countryCodes

,Country,Officialstatename,InternetccTLD,iso2,iso3
0,AFGHANISTAN,The Islamic Republic of Afghanistan,.af,AF,AFG
1,ALBANIA,The Republic of Albania,.al,AL,ALB
2,ALGERIA,The People's Democratic Republic of Algeria,.dz,DZ,DZA
3,ANGOLA,The Republic of Angola,.ao,AO,AGO
4,ANTIGUA AND BARBUDA,Antigua and Barbuda,.ag,AG,ATG
...,...,...,...,...,...
166,UZBEKISTAN,The Republic of Uzbekistan,.uz,UZ,UZB
167,VIET NAM,The Socialist Republic of Viet Nam,.vn,VN,VNM
168,YEMEN,The Republic of Yemen,.ye,YE,YEM
169,ZAMBIA,The Republic of Zambia,.zm,ZM,ZMB
170,ZIMBABWE,The Republic of Zimbabwe,.zw,ZW,ZWE

In [ ]:
data.shape,countryCodes.shape

((191, 8), (171, 5))

In [ ]:
# para limpiar los datos de countries in 'countryCodes' pero no en 'data'
onlyCodes=set(countryCodes.Country)-set(data.Country)
onlyCodes

{'BAHAMAS (THE)',
 'CENTRAL AFRICAN REPUBLIC (THE)',
 'COMOROS (THE)',
 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
 'CONGO (THE)',
 "C√îTE D'IVOIRE",
 'DOMINICAN REPUBLIC (THE)',
 'ESWATINI',
 'GAMBIA (THE)',
 'KOREA (THE REPUBLIC OF)',
 "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
 'MOLDOVA (THE REPUBLIC OF)',
 'NETHERLANDS (THE)',
 'NIGER (THE)',
 'PHILIPPINES (THE)',
 'RUSSIAN FEDERATION (THE)',
 'SUDAN (THE)',
 'TANZANIA, THE UNITED REPUBLIC OF',
 'TURKEY',
 'UNITED ARAB EMIRATES (THE)',
 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
 'UNITED STATES MINOR OUTLYING ISLANDS (THE)'}

In [ ]:
# Countries in 'data' but NOT in 'countryCodes'
onlyData=set(data.Country)-set(countryCodes.Country)
onlyData

{'ANDORRA',
 'BAHAMAS',
 'CENTRAL AFRICAN REPUBLIC',
 'COMOROS',
 'CONGO',
 'CONGO (DEMOCRATIC REPUBLIC OF THE)',
 "CÔTE D'IVOIRE",
 'DOMINICA',
 'DOMINICAN REPUBLIC',
 'ERITREA',
 'ESWATINI (KINGDOM OF)',
 'GAMBIA',
 'HONG KONG, CHINA (SAR)',
 'ISRAEL',
 'KIRIBATI',
 'KOREA (REPUBLIC OF)',
 "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
 'LIECHTENSTEIN',
 'MARSHALL ISLANDS',
 'MOLDOVA (REPUBLIC OF)',
 'NETHERLANDS',
 'NIGER',
 'PALAU',
 'PALESTINE, STATE OF',
 'PHILIPPINES',
 'RUSSIAN FEDERATION',
 'SAINT KITTS AND NEVIS',
 'SAINT LUCIA',
 'SAINT VINCENT AND THE GRENADINES',
 'SAN MARINO',
 'SOUTH AFRICA',
 'SUDAN',
 'SYRIAN ARAB REPUBLIC',
 'TANZANIA (UNITED REPUBLIC OF)',
 'TONGA',
 'TUVALU',
 'TÜRKIYE',
 'UNITED ARAB EMIRATES',
 'UNITED KINGDOM',
 'UNITED STATES',
 'VANUATU',
 'VENEZUELA (BOLIVARIAN REPUBLIC OF)'}

In [ ]:
!pip install thefuzz

Requirement already satisfied: thefuzz in /usr/local/lib/python3.10/dist-packages (0.22.1)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from thefuzz) (3.9.1)

In [ ]:
from thefuzz import process as fz

# look for a country in OnlyCodes and return the most similar
[(c,fz.extractOne(c,onlyData)) for c in sorted(onlyCodes)]

[('BAHAMAS (THE)', ('BAHAMAS', 90)),
 ('CENTRAL AFRICAN REPUBLIC (THE)', ('CENTRAL AFRICAN REPUBLIC', 95)),
 ('COMOROS (THE)', ('COMOROS', 90)),
 ('CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
  ('CONGO (DEMOCRATIC REPUBLIC OF THE)', 95)),
 ('CONGO (THE)', ('CONGO', 90)),
 ("C√îTE D'IVOIRE", ("CÔTE D'IVOIRE", 96)),
 ('DOMINICAN REPUBLIC (THE)', ('DOMINICAN REPUBLIC', 95)),
 ('ESWATINI', ('ESWATINI (KINGDOM OF)', 90)),
 ('GAMBIA (THE)', ('GAMBIA', 90)),
 ('KOREA (THE REPUBLIC OF)', ('KOREA (REPUBLIC OF)', 95)),
 ("LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
  ("LAO PEOPLE'S DEMOCRATIC REPUBLIC", 95)),
 ('MOLDOVA (THE REPUBLIC OF)', ('MOLDOVA (REPUBLIC OF)', 95)),
 ('NETHERLANDS (THE)', ('NETHERLANDS', 95)),
 ('NIGER (THE)', ('NIGER', 90)),
 ('PHILIPPINES (THE)', ('PHILIPPINES', 95)),
 ('RUSSIAN FEDERATION (THE)', ('RUSSIAN FEDERATION', 95)),
 ('SUDAN (THE)', ('SUDAN', 90)),
 ('TANZANIA, THE UNITED REPUBLIC OF', ('TANZANIA (UNITED REPUBLIC OF)', 95)),
 ('TURKEY', ('TÜRKIYE', 67)),
 ('UNITED ARAB EMIRATES (THE)', ('UNITED ARAB EMIRATES', 95)),
 ('UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
  ('UNITED KINGDOM', 90)),
 ('UNITED STATES MINOR OUTLYING ISLANDS (THE)', ('UNITED STATES', 90))]

In [ ]:
#keeping the best ones
[(c,fz.extractOne(c, onlyData)) for c in sorted(onlyCodes)
 if fz.extractOne(c, onlyData)[1]>=67]

[('BAHAMAS (THE)', ('BAHAMAS', 90)),
 ('CENTRAL AFRICAN REPUBLIC (THE)', ('CENTRAL AFRICAN REPUBLIC', 95)),
 ('COMOROS (THE)', ('COMOROS', 90)),
 ('CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
  ('CONGO (DEMOCRATIC REPUBLIC OF THE)', 95)),
 ('CONGO (THE)', ('CONGO', 90)),
 ("C√îTE D'IVOIRE", ("CÔTE D'IVOIRE", 96)),
 ('DOMINICAN REPUBLIC (THE)', ('DOMINICAN REPUBLIC', 95)),
 ('ESWATINI', ('ESWATINI (KINGDOM OF)', 90)),
 ('GAMBIA (THE)', ('GAMBIA', 90)),
 ('KOREA (THE REPUBLIC OF)', ('KOREA (REPUBLIC OF)', 95)),
 ("LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
  ("LAO PEOPLE'S DEMOCRATIC REPUBLIC", 95)),
 ('MOLDOVA (THE REPUBLIC OF)', ('MOLDOVA (REPUBLIC OF)', 95)),
 ('NETHERLANDS (THE)', ('NETHERLANDS', 95)),
 ('NIGER (THE)', ('NIGER', 90)),
 ('PHILIPPINES (THE)', ('PHILIPPINES', 95)),
 ('RUSSIAN FEDERATION (THE)', ('RUSSIAN FEDERATION', 95)),
 ('SUDAN (THE)', ('SUDAN', 90)),
 ('TANZANIA, THE UNITED REPUBLIC OF', ('TANZANIA (UNITED REPUBLIC OF)', 95)),
 ('TURKEY', ('TÜRKIYE', 67)),
 ('UNITED ARAB EMIRATES (THE)', ('UNITED ARAB EMIRATES', 95)),
 ('UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
  ('UNITED KINGDOM', 90)),
 ('UNITED STATES MINOR OUTLYING ISLANDS (THE)', ('UNITED STATES', 90))]

In [ ]:

changesCodes={c:fz.extractOne(c, onlyData)[0]
                 for c in sorted(onlyCodes)
                 if fz.extractOne(c, onlyData)[1] >=67}
#dict of matches
changesCodes

{'BAHAMAS (THE)': 'BAHAMAS',
 'CENTRAL AFRICAN REPUBLIC (THE)': 'CENTRAL AFRICAN REPUBLIC',
 'COMOROS (THE)': 'COMOROS',
 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)': 'CONGO (DEMOCRATIC REPUBLIC OF THE)',
 'CONGO (THE)': 'CONGO',
 "C√îTE D'IVOIRE": "CÔTE D'IVOIRE",
 'DOMINICAN REPUBLIC (THE)': 'DOMINICAN REPUBLIC',
 'ESWATINI': 'ESWATINI (KINGDOM OF)',
 'GAMBIA (THE)': 'GAMBIA',
 'KOREA (THE REPUBLIC OF)': 'KOREA (REPUBLIC OF)',
 "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
 'MOLDOVA (THE REPUBLIC OF)': 'MOLDOVA (REPUBLIC OF)',
 'NETHERLANDS (THE)': 'NETHERLANDS',
 'NIGER (THE)': 'NIGER',
 'PHILIPPINES (THE)': 'PHILIPPINES',
 'RUSSIAN FEDERATION (THE)': 'RUSSIAN FEDERATION',
 'SUDAN (THE)': 'SUDAN',
 'TANZANIA, THE UNITED REPUBLIC OF': 'TANZANIA (UNITED REPUBLIC OF)',
 'TURKEY': 'TÜRKIYE',
 'UNITED ARAB EMIRATES (THE)': 'UNITED ARAB EMIRATES',
 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)': 'UNITED KINGDOM',
 'UNITED STATES MINOR OUTLYING ISLANDS (THE)': 'UNITED STATES'}

In [ ]:
#Replacing in countryCodes
countryCodes.replace(to_replace={'Country':changesCodes},inplace=True)

In [ ]:
# second try

onlyCodes=set(countryCodes.Country)-set(data.Country)
onlyData=set(data.Country)-set(countryCodes.Country)
[(c,fz.extractOne(c,onlyData )) for c in sorted(onlyCodes)]

[]

In [ ]:
datacodes=data.merge(countryCodes)
datacodes

,Hdi_Rank,Country,Expected_Years_Of_Schooling,Gni_Per_Capita_Rank_Minus_Hdi_Rank,Gross_National_Income__Per_Capita,Human_Development_Index__,Life_Expectancy_At_Birth,Mean_Years_Of_Schooling,Officialstatename,InternetccTLD,iso2,iso3
0,1.0,SWITZERLAND,16.500299,5,66933.004540,0.962,83.9872,13.859660,The Swiss Confederation,.ch,CH,CHE
1,2.0,NORWAY,18.185200,6,64660.106220,0.961,83.2339,13.003630,The Kingdom of Norway,.no,NO,NOR
2,3.0,ICELAND,19.163059,11,55782.049810,0.959,82.6782,13.767170,Iceland,.is,IS,ISL
3,5.0,AUSTRALIA,21.054590,18,49238.433350,0.951,84.5265,12.726820,The Commonwealth of Australia,.au,AU,AUS
4,6.0,DENMARK,18.714800,6,60364.785950,0.948,81.3753,12.960490,The Kingdom of Denmark,.dk,DK,DNK
...,...,...,...,...,...,...,...,...,...,...,...,...
166,187.0,BURUNDI,10.722722,4,731.786709,0.426,61.6627,3.129267,The Republic of Burundi,.bi,BI,BDI
167,188.0,CENTRAL AFRICAN REPUBLIC,8.040172,1,966.058611,0.404,53.8947,4.334000,The Central African Republic,.cf,CF,CAF
168,189.0,NIGER,6.957112,-3,1239.866936,0.400,61.5763,2.116717,The Republic of the Niger,.ne,NE,NER
169,190.0,CHAD,8.035914,-7,1364.169417,0.394,52.5254,2.573774,The Republic of Chad,.td,TD,TCD
170,191.0,SOUTH SUDAN,5.542510,-1,767.787000,0.385,54.9752,5.726140,The Republic of South Sudan,.ss,SS,SSD

In [ ]:
datacodes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Hdi_Rank                            171 non-null    float64
 1   Country                             171 non-null    object
 2   Expected_Years_Of_Schooling         171 non-null    float64
 3   Gni_Per_Capita_Rank_Minus_Hdi_Rank  171 non-null    int64
 4   Gross_National_Income__Per_Capita   171 non-null    float64
 5   Human_Development_Index__           171 non-null    float64
 6   Life_Expectancy_At_Birth            171 non-null    float64
 7   Mean_Years_Of_Schooling             171 non-null    float64
 8   Officialstatename                   171 non-null    object
 9   InternetccTLD                       170 non-null    object
 10  iso2                                170 non-null    object
 11  iso3                                171 non-null    object
dtypes: float64(6), int64(1), object(5)
memory usage: 16.2+ KB

**TERCERO**

In [ ]:
import pandas as pd

fallecimientos = 'https://raw.github.com/Journey-of-Success/TAREA3/main/fallecidosCOVID.csv'
# Leer la tabla
df = pd.read_csv(fallecimientos)
df.head()

  FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID
0  20240317;20220219;63;MASCULINO;Criterio viroló...
1  20240317;20210529;74;MASCULINO;Criterio viroló...
2  20240317;20210623;72;FEMENINO;Criterio SINADEF...
3  20240317;20210824;85;MASCULINO;Criterio invest...
4  20240317;20210627;46;MASCULINO;Criterio viroló...

In [ ]:
save_columns=df.columns.str.split(';')
saving=save_columns[0]

In [ ]:
df.rename(columns={df.columns[0]:'a'},inplace=True)
df=df.a.str.split(';',expand=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220918 entries, 0 to 220917
Data columns (total 10 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       220918 non-null  object
 1   1       220918 non-null  object
 2   2       220918 non-null  object
 3   3       220918 non-null  object
 4   4       220918 non-null  object
 5   5       220918 non-null  object
 6   6       220918 non-null  object
 7   7       220918 non-null  object
 8   8       220918 non-null  object
 9   9       220918 non-null  object
dtypes: object(10)
memory usage: 16.9+ MB

In [ ]:
new={0:saving[0],1:saving[1],2:saving[2],3:saving[3],4:saving[4],5:saving[5],6:saving[6],7:saving[7],8:saving[8],9:saving[9]}
df.rename(columns=new,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220918 entries, 0 to 220917
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   FECHA_CORTE          220918 non-null  object
 1   FECHA_FALLECIMIENTO  220918 non-null  object
 2   EDAD_DECLARADA       220918 non-null  object
 3   SEXO                 220918 non-null  object
 4   CLASIFICACION_DEF    220918 non-null  object
 5   DEPARTAMENTO         220918 non-null  object
 6   PROVINCIA            220918 non-null  object
 7   DISTRITO             220918 non-null  object
 8   UBIGEO               220918 non-null  object
 9   UUID                 220918 non-null  object
dtypes: object(10)
memory usage: 16.9+ MB

In [ ]:
df.head()

,FECHA_CORTE,FECHA_FALLECIMIENTO,EDAD_DECLARADA,SEXO,CLASIFICACION_DEF,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,UUID
0,20240317,20220219,63,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203506
1,20240317,20210529,74,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203532
2,20240317,20210623,72,FEMENINO,Criterio SINADEF,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203584
3,20240317,20210824,85,MASCULINO,Criterio investigación Epidemiológica,TUMBES,TUMBES,TUMBES,240101,212541
4,20240317,20210627,46,MASCULINO,Criterio virológico,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203665

In [ ]:
# Convertir la columna de fecha a tipo datetime
df['FECHA_FALLECIMIENTO'] = pd.to_datetime(df['FECHA_FALLECIMIENTO'])
df.head()

,FECHA_CORTE,FECHA_FALLECIMIENTO,EDAD_DECLARADA,SEXO,CLASIFICACION_DEF,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,UUID
0,20240317,2022-02-19,63,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203506
1,20240317,2021-05-29,74,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203532
2,20240317,2021-06-23,72,FEMENINO,Criterio SINADEF,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203584
3,20240317,2021-08-24,85,MASCULINO,Criterio investigación Epidemiológica,TUMBES,TUMBES,TUMBES,240101,212541
4,20240317,2021-06-27,46,MASCULINO,Criterio virológico,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203665

In [ ]:
# Contar el número de registros por año y mes
df['conteo'] = 1

# Agrupar por año y mes y sumar los conteos
result = df.groupby(['año','mes']).agg({'conteo':'sum'}).reset_index()

# Mostrar el resultado
print(result)

KeyError: 'año'